spring.application.name=rpg

spring.datasource.url=jdbc:postgresql://localhost:5432/simulador
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

# URL do servidor do rival para as batalhas em rede
rival.url=http://localhost:8080/

server.port=8080
server.address=0.0.0.0